# This is a basic workflow to help you get started with Actions

name: SpringBootChecker

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: "* * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: setup
        run: |
          git checkout master
          git pull
          git status

      - name: Run a multi-line script
        shell: bash
        run: |
          echo "Starting..."
          sed -i -E "s/<version>2\.[0-9]\.[0-9]+\.RELEASE</<version>$SPRING_BOOT_VERSION.RELEASE</g" ./pom.xml
          echo "That's it for now. Over and out"
