# This is a basic workflow to help you get started with Actions

name: SpringBootChecker

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: "0 0 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Update Spring Boot version
        id: UPDATE
        run: |
          git config user.name 'SpringBootAutoChecker'
          git config user.email 'SpringBootAutoChecker@users.noreply.github.com'
          sed -i -E "s/<version>2\.[0-9]\.[0-9]+\.RELEASE</<version>2.3.4.RELEASE</g" ./pom.xml
          git add ./pom.xml
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "SECURITY Upgrade Spring Boot and ffp-starter version";
            echo "::set-output name=PULL_REQUEST_NEEDED::1";
          else
            echo "::set-output name=PULL_REQUEST_NEEDED::0";
          fi
      - name: Create Pull Request
        if: ${{ steps.UPDATE.outputs.PULL_REQUEST_NEEDED == 1 }}
        uses: peter-evans/create-pull-request@v3
        with:
          committer: GitHub <noreply@github.com>
          signoff: false
          branch: spring-boot-auto-raise
          delete-branch: true
          title: 'Raise Spring Boot version'
          assignees: alexander-schm
          team-reviewers: |
            owners
